name: A workflow for my hello world file

name: Trigger the workflow on push or pull request but only from main branch
on: push
Jobs: 
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    -uses: actions/checkout@v1
    -uses: ./actions-a
     with:
        MY_NAME: "Deepika"
